table Producción
	lineageTag: 44c84bbc-194c-4cdd-bf41-6e3a04b7be75

	measure 'Sup. (has)' = SUM('superficie y volumen'[hectareas])
		lineageTag: c0e9410b-9b2b-495d-a3c6-9a8fbd84a1ec

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ton físicas' = SUM('superficie y volumen'[ton fisicas])
		lineageTag: e0eec4ad-20c0-4dd3-8211-31da241779db

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'rinde ton/ha' = DIVIDE([ton físicas],[Sup. (has)])
		lineageTag: 1f3c493c-36cb-45e1-9a04-7f6a6aa5791f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ton equiv LF' = SUM('superficie y volumen'[ton equiv lf])
		lineageTag: 32a1b282-06df-4e16-a407-a50b6a20fdd1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Rinde equiv LF' = DIVIDE([ton físicas],[Sup. (has)])
		lineageTag: fa59aef1-cf23-441b-ae60-34f1a00911e1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Toneladas Totales' =
			SUMX(
			'barracudas presupuestos',
			    RELATED('barracudas presupuestos_rindes'[rinde.1]) * RELATED('barracudas presupuestos_superficies'[superficie.1])
			)
		lineageTag: a9968bc5-7200-4914-a3f8-db1f4d89f330

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Value
		isHidden
		formatString: 0
		lineageTag: 460c1b9c-ef18-43d7-8fa1-d98ec55ffba1
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Value]

		annotation SummarizationSetBy = Automatic

	partition Producción = calculated
		mode: import
		source = { 0 }

	annotation PBI_Id = 5454ea2e376f4e0c8b5a44f69f637da6

